### ISSUE TITLE
Disconnect on-chain flow is not allowing to connect to a new one

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/bandada#178]
**Describe the bug**
When I try to disconnect from one wallet address and switch to another one, I can´t do that.

**To Reproduce**

1. Go to 'Homepage
2. Click Get Started > Connect Wallet 
3. (Address 1 connected, now I want to connect to another one)
4. Click Disconnect
5. Click Get Started > Connect Wallet
6. It connects me to the Address 1!

**Expected behavior**
I would expect a Metamask popup to select which wallet I want to get started with.

**Screenshots**
![image](https://user-images.githubusercontent.com/67167307/229737367-d1734afa-03c4-489e-953e-96ea01461833.png)

**Additional context**
- I don´t know if this is relevant after SIWE after Milestone 3.
- Is this connected to clearing the cache?

**Comment by cedoor** [comment]
This particular issue has been solved with SIWE.
