### ISSUE TITLE
Add new staging environment

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/bandada#246]
Need to work with PSE DevOps team.

(i think we'd need something like that)

- [ ] Work with DevOps team to create a new production environment with a new AWS account
- [ ] Setup CI/CD pipeline so main deploys to prod
- [ ] Change DNS records to point to that environment
- [ ] Deploy a new dev environment using current AWS account
- [ ] Setup CI/CD pipeline so dev deploys to dev

**Comment by aguzmant103** [comment]
Move to high if integration with p0tion

**Comment by 0xjei** [comment]
We can mark this issue as closed as we have the staging environment set up correctly and we have access to the logs @vplasencia @aguzmant103
