### ISSUE TITLE
Add error message when description is shorter to 10 characters

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/bandada#274]
![Image](https://github.com/privacy-scaling-explorations/bandada/assets/67167307/3e6363bc-2b32-4dc8-80a3-fa54cb40825a)

![Image](https://github.com/privacy-scaling-explorations/bandada/assets/67167307/bd0feab3-c2f2-4bee-becc-1bc6bd2f8510)

"...I think that happens because the description of the group should be at least 10 characters long `(Describe your group (at least 10 characters).`). Can you click `Back `until you get to the description page, then add a longer description and try again? We should let users know when they write a shorter description and click the `Continue `button."

**Comment by NamanAg0502** [comment]
Hey,

Can you share a different link. This one is not working and showing a blank screen on discord.

**Comment by NamanAg0502** [comment]
Thanks,

> I changed a part of code in "general-info-step.tsx".

```
                       <Input
                            size="lg"
                            minLength={10}
                            value={_groupDescription ?? ""}
                            onChange={(event) => {
                                if (event.target.value.length >= 10) {
                                    setGroupDescription(event.target.value)
                                } else {
                                    Error("Invalid group description")
                                }
                            }}
                            onBlur={() =>
                                onSubmit(
                                    {
                                        ...group,
                                        description: _groupDescription
                                    },
                                    false
                                )
                            }
                        />
```

>I am getting some error while setting this up in my local enviornment.

<img width="500" alt="Screenshot 2023-08-17 at 6 56 23 AM" src="https://github.com/privacy-scaling-explorations/bandada/assets/76512364/6d1bc6ee-6132-44b7-bca5-8c00cb98df60">

> My metamask wallet works for connecting with the application but is unable to sign the connection. Is it due to some missing .env urls or some other error?

**Comment by NamanAg0502** [comment]
> Instead of "Error("Invalid group description")" we can use toast.

Link:  https://chakra-ui.com/docs/components/toast

**Comment by aguzmant103** [comment]
@vplasencia do you want to take a look at this one?

**Comment by vplasencia** [comment]
Hey! @NamanAg0502! Thank you! Yes, you need env variables. In the `apps/api` folder, you will see an `.env.example` file. Copy that info and paste it inside a new file called `.env` there.

**Comment by NamanAg0502** [comment]
Hey @vplasencia,
I had already done that and followed all the steps in the contribute section. Still the error persist.

**Comment by aguzmant103** [comment]
Closed by https://github.com/privacy-scaling-explorations/bandada/pull/283
