### ISSUE TITLE
API does not work properly when merging into main.

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#303]
When merging into main, the `isGroupMember` function in the API does not work properly anymore because it returns false when a member is part of the group. 

This issue seems to be related to cached groups because, apparently, they don't sync correctly each time the main branch is updated.

**Comment by 0xjei** [comment]
My guess is that we are not waiting for this._cacheGroups() to execute (`await` is missing in this [line](https://github.com/privacy-scaling-explorations/bandada/blob/4a279aa06c0f894a91baa3e70af1c2638f7a3e07/apps/api/src/app/groups/groups.service.ts#L43))

@vplasencia

**Comment by 0xjei** [comment]
> My guess is that we are not waiting for this._cacheGroups() to execute (`await` is missing in this [line](https://github.com/privacy-scaling-explorations/bandada/blob/4a279aa06c0f894a91baa3e70af1c2638f7a3e07/apps/api/src/app/groups/groups.service.ts#L43))
> 
> @vplasencia

Potentially, we can study and implement a NestJS caching mechanism. Ref: https://docs.nestjs.com/techniques/caching @vplasencia just for note taking here
