### ISSUE TITLE
Add the `addMembersByApiKey` and `removeMembersByApiKey` functions in the API SDK package

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#308]
It would be very similar to `addMemberByApiKey` and `removeMemberByApiKey`

**Comment by aguzmant103** [comment]
- [ ] Study structure of API-SDK + API-SDK testing
- [ ] Check API to add several members
- [ ] Incorporate API to API-SDK
- [ ] Create tests
