### ISSUE TITLE
Update description of the config parameter in the API SDK

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#320]
The idea is to add `@param config [Axios](https://axios-http.com/docs/req_config) Request config.` instead of `@param config Request config.` in the API SDK here: https://github.com/privacy-scaling-explorations/bandada/blob/main/libs/api-sdk/src/apiSdk.ts#L23C8-L23C37

Context:
https://github.com/privacy-scaling-explorations/bandada/pull/311#discussion_r1345494305

**Comment by Ayoseun** [comment]
Can you assign this to me
