### ISSUE TITLE
Dashboard: List groups starting from the most recently created

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#344]
Right now they are listed ordered alphabetically.

**Comment by tanyas-codes** [comment]
hey ! i love this project ! can i take up this issue?

**Comment by vplasencia** [comment]
Hey @tanyas-codes thank you. Yes, sure. Do you want me to assign you this issue?

**Comment by tanyas-codes** [comment]
yes !

**Comment by tanyas-codes** [comment]
hey ! i am done with listing the groups based on recent creation: 
->Off-chains groups are listed based on recents but the same is not possible for the on-chain groups (on-chain groups  are still getting sorted alphabetically)
->i used console.log to check the api response and their properties, and it seems like there is a" createdAt" property for off-chain groups (through which i was able to sort them)
But the on-chain groups has no  such "createdAt" property returned from the "semaphoreAPI" api response .


I checked the semaphore documentation and there was no mention of any property that returns back the time of creation ,digging deeper i found there might be a way to change the schema and maybe  add a " timestamp " whenever a new block is created so maybe changes ,must be made to the semaphoreAPI
https://docs.semaphore.pse.dev/subgraph
https://docs.semaphore.pse.dev/guides/fetching-data

adding images below which show that off-chain groups are sorted based on latest creation time but not the same for on-chain groups .
<img width="616" alt="console log-onchain" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/bced8ae4-2b12-4d39-82c9-0eeb1045d29d">
<img width="616" alt="consolelog-offchain" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/6ffc3cae-8f45-4b1c-ab81-4b24b17e5ef7">
<img width="1409" alt="off-chain" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/b6b98b5f-6619-4592-828e-7f2a116f6027">
<img width="1409" alt="on-chain" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/867cc583-2d82-46a7-ba0d-0729981003b8">

**Comment by vplasencia** [comment]
Hey @tanyas-codes this is great! Thank you so much! Do you want to create a PR to merge your changes?

**Comment by tanyas-codes** [comment]
thankyou !yes , i will create a PR 

can u add a new issue/bug for the semaphore api ,the on-chain groups are still sorted alphabetically and not based on recent creation.

**Comment by vplasencia** [comment]
Hey! Yes, for now, it's fine to have only the off-chain groups sorted by creation. I will create an issue to do the same for on-chain groups later.
