### ISSUE TITLE
Dashboard background in the groups page

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#345]
The dashboard groups page has a background that starts with pink and then when you scroll it is almost white. Maybe it can be better to have the same pink color in the entire page so it is not so difficult to read the group info that appears almost at the end of the page.

**Comment by tanyas-codes** [comment]
hey ! i have solved this issue ,i'll link an image to show how it looks when the entire page background is in pinkcolour 

PS:-do u just want the groups page to be this colour?
or even the remaining pages except the home page to be of the same pink  colour without gradient?

<img width="1440" alt="pinkbackground" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/72867f93-623f-45da-8232-07d9e3e4e5a7">

**Comment by vplasencia** [comment]
Hey @tanyas-codes it looks nice! By the remaining pages you mean `group` and `new-group`, if so, yes, the other pages too.
