### ISSUE TITLE
Show the credential when it is a credential group

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#346]
When displaying the group information, it would be nice to display the credential of the group, in case it is a credential group.

**Comment by tanyas-codes** [comment]
hey ! Can i know more on what to display here?

currently the credentials property has both id and criteria.

suppose the id:Github followers and criteria:min followers:1

so do u want me to display it as Github followers : min followers:1 ?

also for the design part should i add a new div right under the GroupId div ?

**Comment by tanyas-codes** [comment]
@vplasencia hey,can u reply so i can start working on this?

**Comment by vplasencia** [comment]
Hey @tanyas-codes yes, thanks. Yes, it can be a new div like the Group ID, but instead if `Group ID`, it will be `Credentials` and below something similar to the same you wrote: `Github followers - min followers:1`.

**Comment by tanyas-codes** [comment]
hey! @vplasencia  i am done with this issue!

some of the credentials are too lengthy to fit in a single text line 
Like the git(repo+commits)-image 3 linked below ,
that is why i created two  text input lines ,one to show the id and the other shows the criteria 

the images belowe show how various credentials category are displayed 
<img width="757" alt="test-0" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/9f316940-5cb1-468a-8818-e028ffdc2e75">
<img width="1396" alt="test-1" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/e27965a8-c940-4d44-a8ae-513f1efbf29e">

<img width="757" alt="test-3" src="https://github.com/privacy-scaling-explorations/bandada/assets/107319582/1c1ebf98-4156-4dcd-8a05-3ecafc23bd1f">

**Comment by tanyas-codes** [comment]
hey, @vplasencia if u are okay with how it looks ,would u like me to make a pr for the same?

**Comment by vplasencia** [comment]
Hey! @tanyas-codes

It looks great! Yes, agree, adding two lines is better. 

When displaying the id, could you remove the colon? Then instead of `GITHUB_REPOSITORY_COMMITS:`, it would be `GITHUB_REPOSITORY_COMMITS`.

The rest is perfect! Thank you so much.

**Comment by tanyas-codes** [comment]
Whoops! 🙈 Just realized I accidentally added a colon there! My bad! 😅will definitely change it !
