### ISSUE TITLE
When working with the Bandada infrastructure (dashboard, api or sdk) you can get the 503 server error

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#349]
This is the log in the server:
```
[32m[Nest] 1  - [39m01/07/2024, 1:07:43 PM [32m    LOG[39m [32mGroupsService: 94 groups have been cached[39m
```

That should only happen when the server is initialized. Then it means that the server was restarted without merging into main.

Explore potential issues:
- [ ] Backend deployed environment
- [ ] Cached Group management
- [ ] Accidental errors

**Comment by 0xjei** [comment]
Explore potential issues:
- [ ] Backend deployed environment
- [ ] Cached Group management
- [ ] Accidental errors
