### ISSUE TITLE
Display the error message text instead of the status code

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#396]
## Description

In the dashboard app, it would be nice to display the message of the error so that users can better understand what happened.

The idea would be to replace `alert(error.response.statusText)` with `alert(error.response.data.message)` in the [`bandadaAPI.ts`](https://github.com/privacy-scaling-explorations/bandada/blob/main/apps/dashboard/src/api/bandadaAPI.ts) file.

**Comment by code-Gambler** [comment]
The Issue Seems simple, but my Idea is to create a function like `generateErrorMessage(error.response)` and use it, to reduce code redundancy. Can you assign this issue to me

**Comment by vplasencia** [comment]
Yes, sure. Thank you. I just assigned you this issue ✅

Can you explain more about your idea? 

Right now, the backend is sending the error message, but it's not being displayed properly in the dashboard app.

**Comment by kaksv** [comment]
Let me fork this and have a look.

**Comment by code-Gambler** [comment]
> Yes, sure. Thank you. I just assigned you this issue ✅
> 
> Can you explain more about your idea?
> 
> Right now, the backend is sending the error message, but it's not being displayed properly in the dashboard app.

So basically there are a lot of functions calling the api like `createGroup`, `getGroups` etc., My plan is to create a helper function like createErrorResponse(data) which take the response as the parameter and the shows the an alert using `alert(data.message)` and if `data.message` is empty it will show the generic error message `alert("Some error occurred!")`, this way we modularize the code.

**Comment by vplasencia** [comment]
Hey @code-Gambler it looks great. Feel free to do it like this.

**Comment by code-Gambler** [comment]
I made the changes but do I need to write tests for it?, and when try to `yarn dev`, it says cannot connect to the database:
![image](https://github.com/privacy-scaling-explorations/bandada/assets/98861688/f153c99d-dd99-4c21-8ba5-c9284f5704f5)

**Comment by vplasencia** [comment]
Hey @code-Gambler 

Did you copy the environment variables? You can run this in the root folder of the project:

```bash
cp apps/api/.env.example apps/api/.env
```

**Comment by vplasencia** [comment]
@code-Gambler 

You don't need to write tests for it. You can test it in the dashboard app.

**Comment by code-Gambler** [comment]
PR submitted!
Please have a look

**Comment by kaksv** [comment]
I think there is a PR, but your method works if the error is visible but
you want to modularise.

**Comment by vplasencia** [comment]
Hey @kaksv 

The PR solved this issue correctly, but feel free to always create new [issues](https://github.com/privacy-scaling-explorations/bandada/issues) or [discussions](https://github.com/privacy-scaling-explorations/bandada/discussions) to improve the Bandada infrastructure. Thank you so much for your comments.

Every suggestion is highly appreciated.
