### ISSUE TITLE
Add Bandada repository link to the API Docs

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#403]
## Description

The idea is to add the Bandada GitHub repository link to the API Docs: https://api.bandada.pse.dev/

It would be like in the Bandada Dashboard: https://bandada.pse.dev/

It could be at the top right. Other suggestions are also appreciated.

**Comment by MAGICXPLUS** [comment]
Y

**Comment by intldds** [comment]
I would like to take this if possible -- top right sounds good :)

**Comment by vplasencia** [comment]
Hey! @intldds 

Sounds great! Go ahead. I just assigned you the issue. Let us know if you need help.

**Comment by intldds** [comment]
Thanks!

Actually I'm having an error everytime I run "`yarn dev`" or "`npx nest start`" inside the `api` folder. I think I have all dependencies installed @vplasencia

**Comment by code-Gambler** [comment]
I think you have to run `yarn dev` in root directory, not inside the API folder

**Comment by vplasencia** [comment]
Hey @intldds 

These are the steps (In the root project folder):

1- Run `yarn`

2- Run `yarn build`

3- Copy the environment variable by running: `cp apps/api/.env.example apps/api/.env`

4- Run `yarn dev`

https://github.com/privacy-scaling-explorations/bandada?tab=readme-ov-file#-installation

Let us know if you still have issues.

**Comment by intldds** [comment]
Thank you both, it's working now!

I've tried adding the repository link and managed to do so; however, the `DocumentBuilder` class is very rigid and doesn't allow me to change the color or increase the size of the text.

The final result would be:

<img width="1425" alt="bandada" src="https://github.com/privacy-scaling-explorations/bandada/assets/80983240/dc88e6ed-16d2-40d5-a2b4-c9ba3a67dde0">


Outside of the `DocumentBuilder` class I was not able to implement it, which would've made easier to make a better UI. Let me know what you think :) @vplasencia

**Comment by vplasencia** [comment]
Hey @intldds 

Yes, it's a bit difficult. Did you take a look at the [`customCss`](https://github.com/privacy-scaling-explorations/bandada/blob/main/apps/api/src/main.ts#L59) and `customJs` or `customJsStr` properties?
https://docs.nestjs.com/openapi/introduction#setup-options

**Comment by intldds** [comment]
> Hey @intldds
> 
> Yes, it's a bit difficult. Did you take a look at the [`customCss`](https://github.com/privacy-scaling-explorations/bandada/blob/main/apps/api/src/main.ts#L59) and `customJs` or `customJsStr` properties? https://docs.nestjs.com/openapi/introduction#setup-options

Great suggestion :) I've ended up following it and put the repository link and icon into `customJsStr` -- it looks cleaner now and easier to make changes (eg change size, color, placement, etc). Here's the [PR](https://github.com/privacy-scaling-explorations/bandada/pull/405) and let me know if you need any changes!
