### ISSUE TITLE
Displaying the Alert multiple times while creating new groups

### ISSUE THREAD

**Issue by code-Gambler** [privacy-scaling-explorations/bandada#404]
**Describe the bug**
When the user creates a new group, a call is made to `createGroup()` function in `apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx` but if this function returns null it displays an error message "Some Error Occurred". However the function `createGroup()` itself is a failsafe function, so in the case of null return value it had already displayed an error message from the server. So in the end the user ends up getting two alerts one from the server and one from `apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx`

**To Reproduce**

1. Go to 'Dashboard'
2. Click on Add Group'
3. Enter the name and description of the group and in the fingerprint duration enter -1
4. Select how big is your group
5. Click continue
6. Click continue
7. Click 'Create Group'
8. See Error

**Expected behavior**
The user should only get one alert box consisting of the server's error message

**Screenshots**
File: `apps/dashboard/src/components/new-group-stepper/final-preview-step.tsx` line:52
![image](https://github.com/privacy-scaling-explorations/bandada/assets/98861688/f46b0a97-c311-4786-9f4d-75b0cc0ff73d)

**Technologies:**

-   Node.js version - 20.11.0
-   NPM version - 10.2.4

**Comment by code-Gambler** [comment]
I will start working on it, I think just removing the alert should fix the issue

**Comment by vplasencia** [comment]
Hey @code-Gambler! Great! Thank you. Do you want me to assign you this issue?

**Comment by code-Gambler** [comment]
Sure!

**Comment by vplasencia** [comment]
Re this issue, I just created this other issue that would be nice to solve too: https://github.com/privacy-scaling-explorations/bandada/issues/407
