### ISSUE TITLE
Add the `min` property to the `Fingerprint duration` input field

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#407]
## Description

The `Fingerprint duration` should never be less than 0, then it would be nice to add the `min` property to the input field so that numbers < 0 are not an option. 

It was pointed out here: https://github.com/privacy-scaling-explorations/bandada/issues/404

Resources:
https://chakra-ui.com/docs/components/number-input#setting-a-minimum-and-maximum-value

**Comment by code-Gambler** [comment]
I would like to work on the issue

**Comment by vplasencia** [comment]
Great! Thanks. I just assigned you this issue.
