### ISSUE TITLE
Prevent `NaN` from being sent as a correct value of `Fingerprint duration` 

### ISSUE THREAD

**Issue by vplasencia** [privacy-scaling-explorations/bandada#414]
## Description

Right now if you type `-` in the `Fingerprint duration` field when creating a group, it will add the value `NaN`. It would be nice to disable the button so that users can see that it's not a correct value for that.

More context: https://github.com/privacy-scaling-explorations/bandada/pull/408#pullrequestreview-1899604462, https://github.com/privacy-scaling-explorations/bandada/pull/408#issuecomment-1970954040.

**Comment by vplasencia** [comment]
Hey @Ayoseun! Thank you for the interest. The issue is already assigned. I will ping you when we have new similar issues in case you want to take any.

**Comment by Ayoseun** [comment]
Thanks
