### ISSUE TITLE
Broken Discord Links

### ISSUE THREAD

**Issue by omahs** [privacy-scaling-explorations/bandada#421]
Hi, in the repo there are broken links directing to **https://pse.dev/discord**
The page could be fixed or I can also open a PR and update those links to **https://discord.com/invite/sF5CT5rzrR**

**Comment by vplasencia** [comment]
Hey @omahs! Thank you for pointing it out. Yes, feel free to open a PR. Should I assign you this issue?

**Comment by omahs** [comment]
@vplasencia Sure! Just opened the PR!
