### ISSUE TITLE
Allow admins to create reputation groups in the dashboard

### ISSUE THREAD

**Issue by cedoor** [privacy-scaling-explorations/bandada#48]
List:
- [x] #49 
- [x] #189 
- [x] #190 
- [x] #191 
- [x] #188  (Design Team)

**Comment by rachelaux** [comment]
Remind me, when is this due? Not during the current grant period right?

**Comment by cedoor** [comment]
> Remind me, when is this due? Not during the current grant period right?

In Dec/Jan, after we complete Goals 2 and 4.
