### ISSUE TITLE
Design components/user flow for users to create folders and archive groups

### ISSUE THREAD

**Issue by rachelaux** [privacy-scaling-explorations/bandada#63]

**Comment by rachelaux** [comment]
This is going to take a bit more time than I have in my schedule tomorrow. Are folders and the ability to archive requirements for your grant @Insun35 and @jdhyun09? Can the two of you + @cedoor assign priority to this task? Thank you!

**Comment by cedoor** [comment]
> This is going to take a bit more time than I have in my schedule tomorrow. Are folders and the ability to archive requirements for your grant @Insun35 and @jdhyun09? Can the two of you + @cedoor assign priority to this task? Thank you!

They are not requirements. We can assign low priority to this task imo!

**Comment by rachelaux** [comment]
cool, thanks @cedoor! Would you move this card to the backlog at this point? A different way of asking the same question: where do you put cards that contain tasks that are not a current priority?

**Comment by cedoor** [comment]
> cool, thanks @cedoor! Would you move this card to the backlog at this point? A different way of asking the same question: where do you put cards that contain tasks that are not a current priority?

Yes, the backlog is the right place imo!
